### ISSUE TITLE
Ensure builds are working on Windows

### ISSUE THREAD

**Issue by pento** [PonyEdit/PonyEdit#29]
There are (or will be) at least a handful of things to do:

- [ ] Update libssh/openssl DLLs (#19)
- [ ] Update the installer builder for any new syntax highlighting files (#26)
- [ ] Make .ssh/config support work with PuTTY config (#23)
- [ ] Work with known_hosts file (#31)
